"""Generate packages/shared_types/types/index.ts from the Pydantic models.

Run: python packages/shared_types/generate_types.py
Or:  make generate-types
"""

from __future__ import annotations

import sys
from pathlib import Path

# Allow the script to be run from any directory.
sys.path.insert(0, str(Path(__file__).resolve().parent))

from models.analytics import AnalyticsSummary, PlayerAnalytics, ZoneDistribution  # noqa: E402
from models.job import Job, JobStatus  # noqa: E402
from models.telemetry import Detection, TelemetryDocument, TelemetryFrame  # noqa: E402

# ─── type-map helpers ──────────────────────────────────────────────────────────

_PYTHON_TO_TS: dict[str, str] = {
    "string": "string",
    "integer": "number",
    "number": "number",
    "boolean": "boolean",
    "null": "null",
}


def _ts_type(schema: dict) -> str:  # type: ignore[type-arg]
    """Convert a single JSON Schema type entry to a TypeScript type string."""
    if "anyOf" in schema:
        parts = [_ts_type(s) for s in schema["anyOf"]]
        return " | ".join(parts)
    if "allOf" in schema:
        ref = schema["allOf"][0].get("$ref", "")
        return _ref_name(ref)
    if "$ref" in schema:
        return _ref_name(schema["$ref"])
    kind = schema.get("type", "unknown")
    if kind == "array":
        # Fixed-length tuple: prefixItems present
        if "prefixItems" in schema:
            items_ts = ", ".join(_ts_type(s) for s in schema["prefixItems"])
            return f"[{items_ts}]"
        items = schema.get("items", {})
        return f"{_ts_type(items)}[]"
    if kind == "object":
        return "Record<string, unknown>"
    return _PYTHON_TO_TS.get(kind, "unknown")


def _ref_name(ref: str) -> str:
    return ref.split("/")[-1]


def _render_interface(name: str, schema: dict) -> str:  # type: ignore[type-arg]
    """Render a Pydantic model as a TypeScript interface."""
    lines = [f"export interface {name} {{"]
    required = set(schema.get("required", []))
    for prop, spec in schema.get("properties", {}).items():
        optional = "" if prop in required else "?"
        ts = _ts_type(spec)
        lines.append(f"  {prop}{optional}: {ts};")
    lines.append("}")
    return "\n".join(lines)


def _render_string_union(name: str, values: list[str]) -> str:
    joined = " | ".join(f"'{v}'" for v in values)
    return f"export type {name} = {joined};"


# ─── models to emit (order matters for readability) ───────────────────────────

STRING_UNIONS = [
    ("JobStatus", list(JobStatus)),
]

MODELS = [
    ("Job", Job),
    ("ZoneDistribution", ZoneDistribution),
    ("PlayerAnalytics", PlayerAnalytics),
    ("AnalyticsSummary", AnalyticsSummary),
    ("Detection", Detection),
    ("TelemetryFrame", TelemetryFrame),
    ("TelemetryDocument", TelemetryDocument),
]

HEADER = "// Auto-generated by packages/shared_types/generate_types.py. Do not edit by hand."


def generate() -> str:
    blocks = [HEADER]
    for name, values in STRING_UNIONS:
        blocks.append(_render_string_union(name, values))
    for name, model in MODELS:
        schema = model.model_json_schema()
        blocks.append(_render_interface(name, schema))
    return "\n\n".join(blocks) + "\n"


def main() -> None:
    out = Path(__file__).resolve().parent / "types" / "index.ts"
    out.parent.mkdir(parents=True, exist_ok=True)
    content = generate()
    out.write_text(content, encoding="utf-8")


if __name__ == "__main__":
    main()
